// Category color map
const CATEGORY_COLORS = {
  DePIN: "#d1fae5",
  Wallet: "#e0f2fe",
  AI: "#ede9fe",
  DApp: "#fef3c7",
  L1: "#fee2e2",
  "Cross Chain": "#ecfeff"
};


const projects = [
  {
    id: "stratos-network",
    name: "Stratos Network",
    category: ["DePIN"],
    intro: "Building the next generation of decentralized data mesh for #Web3 #DePIN",
    date: "2024-12-30",
    round: "Not Started",
    status: "Upcoming",
    website: "https://www.thestratos.org",
    twitter: "https://x.com/Stratos_Network",
    icon: "icons/stratos-network.png"
  },
  {
    id: "push-protocol",
    name: "Push Protocol",
    category: ["Wallet"],
    intro: "The communication layer of web3. Powering decentralized notifications & chats for wallets",
    date: "",
    round: "",
    status: "",
    website: "https://push.org",
    twitter: "https://x.com/pushprotocol",
    icon: "icons/push-protocol.png"
  },
  {
    id: "graphlinq-chain",
    name: "GraphLinq Chain",
    category: ["DAppAI"],
    intro: "The no-code blockchain for Web3 automation, dApps & AI",
    date: "",
    round: "",
    status: "",
    website: "https://graphlinq.io",
    twitter: "https://x.com/graphlinq_proto",
    icon: "icons/graphlinq-chain.png"
  },
  {
    id: "blackfort",
    name: "BlackFort",
    category: ["L1"],
    intro: "POSA Validation, EVM Core, Layer 1 blockchain by Blackfort. Secure, scalable and decentralised",
    date: "",
    round: "",
    status: "",
    website: "https://blackfort.exchange",
    twitter: "https://x.com/BlackFortBXN",
    icon: "icons/blackfort.png"
  },
  {
    id: "fury",
    name: "Fury",
    category: ["Cross Chain"],
    intro: "Your favorite Cross-Chain Laundromat. Social Commentary through NFTs",
    date: "",
    round: "Not Started",
    status: "Upcoming",
    website: "",
    twitter: "https://x.com/FuryMetaa",
    icon: "icons/fury.png"
  },
  {
    id: "mintlayer",
    name: "Mintlayer",
    category: ["Cross Chain"],
    intro: "Unlock Bitcoin to DeFi with Native BTC Cross-Chain Swaps",
    date: "",
    round: "",
    status: "",
    website: "https://www.mintlayer.org",
    twitter: "https://x.com/mintlayer",
    icon: "icons/mintlayer.png"
  },
  {
    id: "swell",
    name: "Swell",
    category: ["Restaking"],
    intro: "The restaking chain, powered by Proof of Restake. Built on the Superchain.",
    date: "",
    round: "",
    status: "",
    website: "https://www.swellnetwork.io",
    twitter: "https://x.com/swellnetworkio",
    icon: "icons/swell.png"
  },
  {
    id: "nosana",
    name: "Nosana",
    category: ["AI"],
    intro: "Where AI meets decentralized compute",
    date: "",
    round: "",
    status: "",
    website: "https://nosana.com",
    twitter: "https://x.com/nosana_ai",
    icon: "icons/nosana.png"
  },
  {
    id: "sirkl-io",
    name: "SIRKL.io",
    category: ["Wallet"],
    intro: "Wallet to Wallet Multi-Chain Chat App",
    date: "",
    round: "",
    status: "",
    website: "https://sirkl.io",
    twitter: "https://x.com/SIRKL_io",
    icon: "icons/sirkl-io.png"
  },
  {
    id: "wmtx-world-mobile-token",
    name: "WMTx: World Mobile Token",
    category: ["Connectivity"],
    intro: "Powering the future of connectivity",
    date: "",
    round: "",
    status: "",
    website: "https://worldmobiletoken.com",
    twitter: "https://x.com/wmtoken",
    icon: "icons/wmtx-world-mobile-token.png"
  },
  {
    id: "honeyfun-ai",
    name: "HoneyFun AI",
    category: ["AI AGENT"],
    intro: "First AI Agents + Pumpfun Protocol on Berachain",
    date: "",
    round: "",
    status: "",
    website: "https://testnet.honey.fun",
    twitter: "https://x.com/honeydotfun",
    icon: "icons/honeyfun-ai.png"
  },
  {
    id: "stader-labs",
    name: "Stader Labs",
    category: ["Liquid Stakingdefi"],
    intro: "Non-custodial & secure liquid staking",
    date: "",
    round: "",
    status: "",
    website: "https://www.staderlabs.com",
    twitter: "https://x.com/staderlabs",
    icon: "icons/stader-labs.png"
  },
  {
    id: "creo-engine",
    name: "Creo Engine",
    category: ["GameFi"],
    intro: "The Universal Community Driven Gaming Ecosystem with Interoperable Assets! 150+ Games Live!",
    date: "",
    round: "",
    status: "",
    website: "https://www.creoengine.com",
    twitter: "https://x.com/creo_engine",
    icon: "icons/creo-engine.png"
  },
  {
    id: "krayon",
    name: "Krayon",
    category: ["L2"],
    intro: "The world’s most rewarding crypto-first payments firm & L2. From remittances to transfers, easy, fast and borderless",
    date: "",
    round: "",
    status: "",
    website: "https://www.krayondigital.com",
    twitter: "https://x.com/krayon_digital",
    icon: "icons/krayon.png"
  },
  {
    id: "treehouse",
    name: "Treehouse",
    category: ["DeFi"],
    intro: "The Decentralized Fixed Income Layer enabling fixed income products & primitives for digital assets.",
    date: "",
    round: "",
    status: "",
    website: "https://www.treehouse.finance",
    twitter: "https://x.com/TreehouseFi",
    icon: "icons/treehouse.png"
  },
  {
    id: "gunzilla-games",
    name: "Gunzilla Games",
    category: ["GameFi"],
    intro: "Developers of the AAA Extraction Royale @playoffthegrid",
    date: "",
    round: "",
    status: "",
    website: "https://gunzillagames.com",
    twitter: "https://x.com/GunzillaGames",
    icon: "icons/gunzilla-games.png"
  },
  {
    id: "memes-lab",
    name: "Memes Lab",
    category: ["NFTInfrastructure"],
    intro: "Memes Infrastructure & App for coins to flourish and users to earn. Built on @ton_blockchain",
    date: "",
    round: "",
    status: "",
    website: "",
    twitter: "https://x.com/memeslabxyz",
    icon: "icons/memes-lab.png"
  },
  {
    id: "rewardable",
    name: "Rewardable",
    category: ["Task to Earn"],
    intro: "Turn your spare time into extra cash with simple online tasks and micro-jobs. Earn money whenever and wherever you like",
    date: "",
    round: "",
    status: "",
    website: "https://www.rewardable.app",
    twitter: "https://x.com/rewardable_app",
    icon: "icons/rewardable.png"
  },
  {
    id: "inspir3",
    name: "Inspir3",
    category: ["NFT"],
    intro: "Mint your Founder NFTs. Get early access to Inspir3 and start earning.",
    date: "",
    round: "",
    status: "",
    website: "https://www.inspir3.io",
    twitter: "https://x.com/Inspir3NFT",
    icon: "icons/inspir3.png"
  },
  {
    id: "joinn-finance",
    name: "Joinn Finance",
    category: ["DeFi"],
    intro: "Seamless Access to Onchain Real World Assets.",
    date: "",
    round: "",
    status: "",
    website: "https://joinn.io",
    twitter: "https://x.com/JoinnFinance",
    icon: "icons/joinn-finance.png"
  },
  {
    id: "autolayer",
    name: "AutoLayer",
    category: ["Marketplace"],
    intro: "The Largest Restaking Marketplace",
    date: "",
    round: "",
    status: "",
    website: "https://autolayer.io",
    twitter: "https://x.com/AutoLayer",
    icon: "icons/autolayer.png"
  },
  {
    id: "mintera",
    name: "Mintera",
    category: ["NFT"],
    intro: "Mintera is an ambitious digital investment firm based out of Paris, France.",
    date: "",
    round: "",
    status: "",
    website: "https://mintera.co",
    twitter: "https://x.com/mintera_co",
    icon: "icons/mintera.png"
  },
  {
    id: "skate",
    name: "Skate",
    category: ["Infrastructure"],
    intro: "The infrastructure for Stateless Apps.",
    date: "",
    round: "",
    status: "",
    website: "https://www.skatechain.org",
    twitter: "https://x.com/skate_chain",
    icon: "icons/skate.png"
  },
  {
    id: "nomoex-global",
    name: "Nomoex Global",
    category: ["Exchange"],
    intro: "World's Smartest Blockchain Eco-System & Digital assets Exchange. Made For Traders by Trader.",
    date: "",
    round: "",
    status: "",
    website: "https://www.nomoex.com",
    twitter: "https://www.nomoex.com/en_US/",
    icon: "icons/nomoex-global.png"
  },
  {
    id: "affi-network",
    name: "Affi Network",
    category: ["SocialFi"],
    intro: "Web3 Loyalty Platform | White Label | Streamlining Incentive Distribution & Management for Web3 Businesses",
    date: "",
    round: "",
    status: "",
    website: "https://www.affi.network",
    twitter: "https://x.com/Affi_Network",
    icon: "icons/affi-network.png"
  },
  {
    id: "din",
    name: "DIN",
    category: ["AI"],
    intro: "The First Modular AI-Native Data Pre-Processing Layer Backed by @BinanceLabs",
    date: "",
    round: "",
    status: "",
    website: "https://din.lol",
    twitter: "https://x.com/din_lol_",
    icon: "icons/din.png"
  },
  {
    id: "kelp-dao",
    name: "Kelp DAO",
    category: ["Liquid Staking"],
    intro: "The first integrated airdrop vault is now live with Gain • Innovating liquid restaking on @eigenlayer for @ethereum",
    date: "",
    round: "",
    status: "",
    website: "https://kelpdao.xyz",
    twitter: "https://x.com/KelpDAO",
    icon: "icons/kelp-dao.png"
  },
  {
    id: "tars-ai",
    name: "TARS AI",
    category: ["Infrastructure"],
    intro: "AI Infrastructure Protocol on Solana, backed by @Solana",
    date: "",
    round: "",
    status: "",
    website: "https://tars.pro",
    twitter: "https://x.com/tarsprotocol",
    icon: "icons/tars-ai.png"
  },
  {
    id: "capybara",
    name: "Capybara",
    category: ["MEME"],
    intro: "I’m literally just a capybara. Flying to the moon",
    date: "",
    round: "",
    status: "",
    website: "https://www.capybara.vip",
    twitter: "https://x.com/capybaraonsui",
    icon: "icons/capybara.png"
  },
  {
    id: "roolz",
    name: "RoOLZ",
    category: ["Gaming"],
    intro: "Anime, Games, #10 NFT and $GODL on TON & Telegram.",
    date: "",
    round: "",
    status: "",
    website: "",
    twitter: "https://x.com/Roolznft",
    icon: "icons/roolz.png"
  },
  {
    id: "memefi",
    name: "MemeFi",
    category: ["MEME"],
    intro: "SocialFi meets GameFi on @Lineabuild",
    date: "",
    round: "",
    status: "",
    website: "https://www.memefi.club",
    twitter: "https://x.com/memeficlub",
    icon: "icons/memefi.png"
  },
  {
    id: "supra-oracles",
    name: "Supra Oracles",
    category: ["L1"],
    intro: "Enabling Super dApps with the full vertical integration of all core oracle services into one high-throughput, Multi-VM compatible Layer-1.",
    date: "",
    round: "",
    status: "",
    website: "https://supra.com",
    twitter: "https://twitter.com/SupraOracles",
    icon: "icons/supra-oracles.png"
  },
  {
    id: "assisterr",
    name: "Assisterr",
    category: ["AI"],
    intro: "Building an Infrastructure Layer for Community-Owned AI Models. Testnet with 100 AI agents is live",
    date: "",
    round: "",
    status: "",
    website: "https://www.assisterr.ai",
    twitter: "https://x.com/assisterr",
    icon: "icons/assisterr.png"
  },
  {
    id: "citron-labs",
    name: "Citron Labs",
    category: [],
    intro: "",
    date: "",
    round: "",
    status: "",
    website: "",
    twitter: "",
    icon: "icons/citron-labs.png"
  },
  {
    id: "coffee-coin",
    name: "Coffee Coin",
    category: ["Token"],
    intro: "deranged, caffeinated with shitposting and run by retarded team yes, we fucked up the ticker",
    date: "",
    round: "",
    status: "",
    website: "https://coffeecoin.fun",
    twitter: "https://x.com/CoffeeMemeCoin",
    icon: "icons/coffee-coin.png"
  },
  {
    id: "tea-meme",
    name: "Tea MEME",
    category: ["Token"],
    intro: "cu-$TEA memecoin on #Solana",
    date: "",
    round: "",
    status: "",
    website: "https://teameme.wtf",
    twitter: "https://x.com/TeaMemeCoin",
    icon: "icons/tea-meme.png"
  },
  {
    id: "spherex",
    name: "SphereX",
    category: ["DEX"],
    intro: "A chain-agnostic perpetual DEX",
    date: "",
    round: "",
    status: "",
    website: "https://www.sx.xyz",
    twitter: "https://x.com/SphereX_XYZ",
    icon: "icons/spherex.png"
  },
  {
    id: "lussa-ai",
    name: "Lussa AI",
    category: ["GamingWeb3"],
    intro: "Lussa: The Final Frontier is a WEB3-oriented NFT PC / Mobile / Console game for real game lovers, enhanced with new dynamics and realistic graphics.",
    date: "",
    round: "",
    status: "",
    website: "https://lussa.io",
    twitter: "https://x.com/Lussaio",
    icon: "icons/lussa-ai.png"
  },
  {
    id: "orion-lumia",
    name: "Orion / Lumia",
    category: [],
    intro: "",
    date: "",
    round: "",
    status: "",
    website: "",
    twitter: "",
    icon: "icons/orion-lumia.png"
  },
  {
    id: "zoth",
    name: "ZOTH",
    category: ["RWA"],
    intro: "Your Portal to Onchain Real World Assets",
    date: "",
    round: "",
    status: "",
    website: "https://t.co",
    twitter: "https://x.com/zothdotio",
    icon: "icons/zoth.png"
  },
  {
    id: "yolo-games",
    name: "Yolo Games",
    category: ["Gaming"],
    intro: "YOLO Games | The Home of Degen Gaming",
    date: "",
    round: "",
    status: "",
    website: "https://yologames.io",
    twitter: "https://x.com/YOLO_Blast",
    icon: "icons/yolo-games.png"
  },
  {
    id: "propy",
    name: "PROPY",
    category: ["AI"],
    intro: "24/7 Real Estate Closings We leverage AI and blockchain technology for smooth and secure transactions",
    date: "",
    round: "",
    status: "",
    website: "https://propy.com",
    twitter: "https://x.com/PropyInc",
    icon: "icons/propy.png"
  },
  {
    id: "earn-m",
    name: "EARN M",
    category: ["DApp"],
    intro: "EARNM Loyalty Ecosystem, powering rewards for online platforms",
    date: "",
    round: "",
    status: "",
    website: "https://www.earnm.com",
    twitter: "https://x.com/earnm_decrypter",
    icon: "icons/earn-m.png"
  },
  {
    id: "match-chain",
    name: "Match Chain",
    category: ["Web3"],
    intro: "DECENTRALIZING AI ON-CHAIN WITH DATA & IDENTITY SOVEREIGNTY",
    date: "",
    round: "",
    status: "",
    website: "https://matchain.io",
    twitter: "https://x.com/matchain_io",
    icon: "icons/match-chain.png"
  },
  {
    id: "astra-nova",
    name: "Astra Nova",
    category: ["Gaming"],
    intro: "Astra Nova is a free-to-play Revolutionary Web3 RPG",
    date: "",
    round: "",
    status: "",
    website: "https://astranova.world",
    twitter: "https://x.com/Astra__Nova",
    icon: "icons/astra-nova.png"
  },
  {
    id: "ultiverse",
    name: "Ultiverse",
    category: ["DAO"],
    intro: "One-stop Game Production and Publishing Platform, powered by AI infrastructure",
    date: "",
    round: "",
    status: "",
    website: "https://link3.to",
    twitter: "https://x.com/UltiverseDAO",
    icon: "icons/ultiverse.png"
  },
  {
    id: "nexgami",
    name: "NexGami",
    category: ["Gaming"],
    intro: "Uniting Traditional Gaming & Web3.0",
    date: "",
    round: "",
    status: "",
    website: "https://www.nexgami.com",
    twitter: "https://x.com/nexgami",
    icon: "icons/nexgami.png"
  },
  {
    id: "lime-ime",
    name: "Lime iME",
    category: ["DeFiAIWallet"],
    intro: "iMe is a messaging smart platform powered by Telegram with Crypto Wallet. Extended Telegram features & DeFi capabilities",
    date: "",
    round: "",
    status: "",
    website: "https://imem.app",
    twitter: "https://x.com/iMePlatform",
    icon: "icons/lime-ime.png"
  },
  {
    id: "paramlabs",
    name: "ParamLabs",
    category: ["Gaming"],
    intro: "Next-Gen Gaming Ecosystem",
    date: "",
    round: "",
    status: "",
    website: "https://paramgaming.com",
    twitter: "https://x.com/ParamLaboratory",
    icon: "icons/paramlabs.avif"
  },
  {
    id: "darewise-opal",
    name: "Darewise OPAL",
    category: ["Metaverse"],
    intro: "Metaverse Technology company building on #bitcoin",
    date: "",
    round: "",
    status: "",
    website: "https://darewise.com",
    twitter: "https://x.com/Darewise",
    icon: "icons/darewise-opal.png"
  },
  {
    id: "cookie3-kol",
    name: "Cookie3 KOL",
    category: ["AIdata"],
    intro: "The first MarketingFi & AI Data Layer for users, creators, and businesses.",
    date: "",
    round: "",
    status: "",
    website: "https://www.cookie3.com",
    twitter: "https://x.com/cookie3",
    icon: "icons/cookie3-kol.png"
  },
  {
    id: "humans-ai",
    name: "Humans AI",
    category: ["AI"],
    intro: "Creators of the Blockchain of AIs. Builders of the AIverse",
    date: "",
    round: "",
    status: "",
    website: "https://humans.ai",
    twitter: "https://x.com/humansdotai",
    icon: "icons/humans-ai.png"
  },
  {
    id: "daopeople",
    name: "DaoPeople",
    category: ["DAO"],
    intro: "The world's first social network created specifically for the Web 3.0 environment, which is suitable for both business and crypto communities",
    date: "",
    round: "",
    status: "",
    website: "",
    twitter: "https://x.com/DAOPEOPLE",
    icon: "icons/daopeople.png"
  },
  {
    id: "cryptograd",
    name: "CryptoGrad",
    category: ["AI"],
    intro: "AI-Powered infrastructure for Web3 | Harness the Power of Crypto AI with CG Network",
    date: "",
    round: "",
    status: "",
    website: "https://cryptograd.ai",
    twitter: "https://x.com/cryptogradai",
    icon: "icons/cryptograd.png"
  },
  {
    id: "arthera-chain",
    name: "Arthera Chain",
    category: ["L1"],
    intro: "Arthera, next-gen EVM L1 Blockchain with Gas Pass",
    date: "",
    round: "",
    status: "",
    website: "https://www.arthera.net",
    twitter: "https://x.com/artherachain",
    icon: "icons/arthera-chain.png"
  },
  {
    id: "dapplabs-dapppad",
    name: "DappLabs DappPad",
    category: ["LAUNCHPAD"],
    intro: "Simplifying Web3 via Account Abstraction on Layer2",
    date: "",
    round: "",
    status: "",
    website: "https://side.xyz",
    twitter: "https://x.com/Dappadofficial",
    icon: "icons/dapplabs-dapppad.png"
  },
  {
    id: "parti-com",
    name: "Parti.com",
    category: ["SocialFi"],
    intro: "SocialFi, Live Streaming, Web3 Gaming Competitions, Commerce, and Engagement with 100% On-Chain Rewards",
    date: "",
    round: "",
    status: "",
    website: "https://parti.com",
    twitter: "https://x.com/jointheparti",
    icon: "icons/parti-com.png"
  },
  {
    id: "nimble",
    name: "Nimble",
    category: ["Network"],
    intro: "The AI OrderBook for Decentralized Training and Inferencing.",
    date: "",
    round: "",
    status: "",
    website: "https://www.nimble.technology",
    twitter: "https://x.com/Nimble_Network",
    icon: "icons/nimble.png"
  },
  {
    id: "overlay",
    name: "Overlay",
    category: ["Data"],
    intro: "Long/short any data stream with a dynamic supply native currency - backed by Polychain, 1kx, ParaFi",
    date: "",
    round: "",
    status: "",
    website: "https://overlay.market",
    twitter: "https://x.com/OverlayProtocol",
    icon: "icons/overlay.png"
  },
  {
    id: "hearts-humans-ai",
    name: "Hearts humans AI",
    category: ["AI"],
    intro: "Creators of the Blockchain of AIs. Builders of the AIverse.",
    date: "",
    round: "",
    status: "",
    website: "https://humans.ai",
    twitter: "https://x.com/humansdotai",
    icon: "icons/hearts-humans-ai.png"
  },
  {
    id: "bluwhale",
    name: "BluWhale",
    category: ["data"],
    intro: "Turn your data into your most valuable asset.",
    date: "",
    round: "",
    status: "",
    website: "https://www.bluwhale.com",
    twitter: "https://x.com/bluwhaleai",
    icon: "icons/bluwhale.png"
  },
  {
    id: "belong",
    name: "Belong",
    category: ["RWADePIN"],
    intro: "Token gating for communities, events, RWA and DePIN",
    date: "",
    round: "",
    status: "",
    website: "https://belong.net",
    twitter: "https://x.com/belongnet",
    icon: "icons/belong.png"
  },
  {
    id: "praise-token",
    name: "Praise Token",
    category: ["SocialFiDApp"],
    intro: "The Token of Appreciation. Have Fun. Earn $PRAISE. Save the World",
    date: "",
    round: "",
    status: "",
    website: "https://praisetoken.io",
    twitter: "https://x.com/praisetoken",
    icon: "icons/praise-token.png"
  },
  {
    id: "logx",
    name: "LogX",
    category: ["DEXDeFi"],
    intro: "Leading perpetuals trading DEX on Layer 2 networks.",
    date: "",
    round: "",
    status: "",
    website: "https://app.logx.trade",
    twitter: "https://x.com/LogX_trade",
    icon: "icons/logx.png"
  },
  {
    id: "pac-finance",
    name: "Pac Finance",
    category: ["defi"],
    intro: "The first self-repaying and hybrid lending protocol on @Blast_L2. Big Bang winner. 100% of Blast developer points & more airdropped to early adopters.",
    date: "",
    round: "",
    status: "",
    website: "https://www.pac.finance",
    twitter: "https://twitter.com/pac_finance?s=20",
    icon: "icons/pac-finance.png"
  },
  {
    id: "arthera",
    name: "Arthera",
    category: ["L1"],
    intro: "Arthera is an EVM-compatible Layer-1 blockchain with native subscriptions, unmatched scalability, and a DAG-based Proof-of-Stake consensus model",
    date: "",
    round: "",
    status: "",
    website: "https://www.arthera.net",
    twitter: "https://twitter.com/artherachain",
    icon: "icons/arthera.png"
  },
  {
    id: "engines-of-fury",
    name: "Engines of Fury",
    category: ["GameFi"],
    intro: "F2P top-down extraction shooter brought by AAA team to web3.",
    date: "",
    round: "",
    status: "",
    website: "https://bit.ly",
    twitter: "https://twitter.com/EnginesOfFury?s=20",
    icon: "icons/engines-of-fury.png"
  },
  {
    id: "koala-wallet",
    name: "Koala Wallet",
    category: ["Wallet"],
    intro: "Our goal? Not just another wallet. Your passport to every crypto ecosystem",
    date: "",
    round: "",
    status: "",
    website: "https://koalawallet.io",
    twitter: "https://twitter.com/koalawallet?s=20a",
    icon: "icons/koala-wallet.png"
  },
  {
    id: "bitbrawl",
    name: "BitBrawl",
    category: ["GameFi"],
    intro: "The platform fighter on Solana. Brawl on your PC or phone using your favorite NFTs and earn $BRAWL",
    date: "",
    round: "",
    status: "",
    website: "https://www.bitbrawl.io",
    twitter: "https://twitter.com/BitBrawlio",
    icon: "icons/bitbrawl.png"
  },
  {
    id: "flowtrade-ai",
    name: "FLOWTRADE.ai",
    category: ["AI"],
    intro: "We are a cutting-edge technology start-up providing innovative AI-driven software solutions,self custody,fully automated,redefining trading.",
    date: "",
    round: "",
    status: "",
    website: "https://flowtrade.ai",
    twitter: "https://twitter.com/flowtrade_ai?s=20",
    icon: "icons/flowtrade-ai.png"
  },
  {
    id: "utgard",
    name: "Utgard",
    category: ["GameFi"],
    intro: "Conquer the north now with $UTG! #Solana",
    date: "",
    round: "",
    status: "",
    website: "https://utgard.io",
    twitter: "https://twitter.com/UtgardPnE?s=20",
    icon: "icons/utgard.png"
  },
  {
    id: "citizend",
    name: "Citizend",
    category: ["Platform"],
    intro: "The community-curated token launch platform of web3. Become #citizend",
    date: "",
    round: "",
    status: "",
    website: "https://citizend.xyz",
    twitter: "https://twitter.com/citizendxyz?s=20",
    icon: "icons/citizend.png"
  },
  {
    id: "ponder-one",
    name: "Ponder.One",
    category: ["BRC20DePIN"],
    intro: "Compare & execute the best of Web3 From EigenLayer restaking | BRC-20 markets | RWA/NFT markets | DePINs | to DeFi solutions. All in ONE place",
    date: "",
    round: "",
    status: "",
    website: "https://ponder.one",
    twitter: "https://twitter.com/Ponder_One",
    icon: "icons/ponder-one.png"
  },
  {
    id: "searchpad",
    name: "Searchpad",
    category: ["pad"],
    intro: "Redefining the future of content creation through AI • Accelerating careers & networks in Web3 • Coming soon",
    date: "",
    round: "",
    status: "",
    website: "https://www.searchpad.app",
    twitter: "https://twitter.com/searchpad_app",
    icon: "icons/searchpad.png"
  },
  {
    id: "destinyx",
    name: "DestinyX",
    category: ["GameFi"],
    intro: "World Class Casino, Sportsbook & Crypto Trading Superapp | Backed by the top VCs including Dragonfly and Razer",
    date: "",
    round: "",
    status: "",
    website: "https://destinyx.com",
    twitter: "https://destinyx.com/",
    icon: "icons/destinyx.png"
  },
  {
    id: "re-al",
    name: "re.al",
    category: ["RWA"],
    intro: "The first permissionless L2 for tokenized RWAs. Built on Arbitrum Orbit.",
    date: "",
    round: "",
    status: "",
    website: "https://www.re.al",
    twitter: "https://twitter.com/real_rwa",
    icon: "icons/re-al.png"
  },
  {
    id: "rwa-finance",
    name: "RWA Finance",
    category: ["RWA"],
    intro: "RWA Marketplace: Effortless and secure trading for tokenized assets #RWA. $RWAS.",
    date: "",
    round: "",
    status: "",
    website: "https://www.rwa-finance.com",
    twitter: "https://twitter.com/RWA_Finance_",
    icon: "icons/rwa-finance.png"
  },
  {
    id: "bowled",
    name: "Bowled",
    category: ["GameFi"],
    intro: "Creating the next-gen of Sportsverse, One game at a time - $BWLD | Backed by @SkyMavisHQ & @YieldGuild",
    date: "",
    round: "",
    status: "",
    website: "https://www.bowled.io",
    twitter: "https://twitter.com/bowleddotio",
    icon: "icons/bowled.png"
  },
  {
    id: "laika-ai",
    name: "Laika AI",
    category: ["AI"],
    intro: "World’s First Web3-Modeled AI Ecosystem |",
    date: "",
    round: "",
    status: "",
    website: "https://www.laika-ai.io",
    twitter: "https://twitter.com/Laika_ai",
    icon: "icons/laika-ai.png"
  },
  {
    id: "kima-network",
    name: "KIMA NETWORK",
    category: ["Interoperability."],
    intro: "The Decentralized Money Transfer Protocol Revolutionizing Financial Interoperability. Backed by @Mastercard's Finsec Innovation Labs. Incubated by @Chain_GPT.",
    date: "",
    round: "",
    status: "",
    website: "https://kima.finance",
    twitter: "https://twitter.com/KimaNetwork",
    icon: "icons/kima-network.png"
  },
  {
    id: "mantra",
    name: "MANTRA",
    category: ["RWA"],
    intro: "Unlocking the $16 Trillion #RWA economy with a regulation-ready blockchain.",
    date: "",
    round: "",
    status: "",
    website: "https://www.mantrachain.io",
    twitter: "https://twitter.com/MANTRA_Chain",
    icon: "icons/mantra.png"
  },
  {
    id: "graphlinq-chain",
    name: "GraphLinq Chain",
    category: ["AI"],
    intro: "The no-code blockchain for Web3 automation, dApps & AI",
    date: "",
    round: "",
    status: "",
    website: "https://graphlinq.io",
    twitter: "https://x.com/graphlinq_proto",
    icon: "icons/graphlinq-chain.png"
  },
  {
    id: "prom",
    name: "Prom",
    category: ["L2"],
    intro: "Modular zkEVM Layer 2. Connecting EVM & Non-EVM worlds through interoperability",
    date: "",
    round: "",
    status: "",
    website: "https://prom.io",
    twitter: "https://twitter.com/prom_io",
    icon: "icons/prom.png"
  },
  {
    id: "singularitydao",
    name: "SingularityDAO",
    category: ["AI"],
    intro: "Non-Custodial DeFi - AI-Powered Quant Strategies",
    date: "",
    round: "",
    status: "",
    website: "https://www.singularitydao.ai",
    twitter: "https://twitter.com/SingularityDAO",
    icon: "icons/singularitydao.png"
  },
  {
    id: "skillfull-ai",
    name: "SkillFull AI",
    category: ["AI"],
    intro: "Skillful AI is an advanced platform that empowers individuals by providing a personalized AI ecosystem. It enables users to stay current with rapid technological advancements, offering customized virtual assistants trained in domain-specific knowledge.",
    date: "",
    round: "",
    status: "",
    website: "https://www.skillfulai.io",
    twitter: "https://twitter.com/SkillfulAI",
    icon: "icons/skillfull-ai.png"
  },
  {
    id: "gullswap",
    name: "GullSwap",
    category: ["DeFi"],
    intro: "",
    date: "March 14, 2024",
    round: "KOL Round",
    status: "Closed",
    website: "",
    twitter: "",
    icon: "icons/gullswap.png"
  },
  {
    id: "metropolis",
    name: "Metropolis",
    category: ["Payment"],
    intro: "Launching projects on every network with confidence",
    date: "",
    round: "",
    status: "",
    website: "https://metal.build",
    twitter: "https://x.com/0xMetropolis",
    icon: "icons/metropolis.png"
  },
  {
    id: "partisia-network",
    name: "Partisia Network",
    category: ["L1"],
    intro: "Partisia Blockchain's #MPC powered Layer 1 blockchain achieves unparalleled scalability, interoperability, and privacy. Unlock the full potential of Web3.",
    date: "",
    round: "",
    status: "",
    website: "https://partisiablockchain.com",
    twitter: "https://twitter.com/partisiampc",
    icon: "icons/partisia-network.png"
  },
  {
    id: "atomiqdefi",
    name: "AtomiqDeFi",
    category: ["DeFi"],
    intro: "AtomiqDeFi unleashes true Bitcoin interoperability via a suite of dApps powered by Atomic Swaps.",
    date: "",
    round: "",
    status: "",
    website: "https://side.xyz",
    twitter: "https://twitter.com/AtomiqDeFi",
    icon: "icons/atomiqdefi.png"
  },
  {
    id: "patex",
    name: "Patex",
    category: ["GameFi"],
    intro: "Patex is the first blockchain ecosystem targeting Latin America, a region with 670M+ people and a $5.5 trillion GDP",
    date: "",
    round: "",
    status: "",
    website: "https://patex.io",
    twitter: "https://twitter.com/patex_ecosystem",
    icon: "icons/patex.png"
  },
  {
    id: "mocaverse",
    name: "Mocaverse",
    category: ["NFT"],
    intro: "Building the largest on-chain cultural economy via a network layer of Account, Identity, Reputation & PointFi",
    date: "",
    round: "",
    status: "",
    website: "https://www.mocaverse.xyz",
    twitter: "https://twitter.com/MocaverseNFT",
    icon: "icons/mocaverse.png"
  },
  {
    id: "aperion",
    name: "Aperion",
    category: ["Payment"],
    intro: "Apeiron is an innovative blend of Roguelite and RTS Card Game, infused with a touch of Doodiness.",
    date: "",
    round: "",
    status: "",
    website: "https://apeironnft.com",
    twitter: "https://twitter.com/ApeironNFT",
    icon: "icons/aperion.png"
  },
  {
    id: "genlayer",
    name: "GenLayer",
    category: ["DApp"],
    intro: "GenLayer is a blockchain that shatters the bounds of smart contracts by making them intelligent and connected to the internet.",
    date: "",
    round: "",
    status: "",
    website: "https://genlayer.com",
    twitter: "https://twitter.com/GenLayer",
    icon: "icons/genlayer.png"
  },
  {
    id: "mystiko",
    name: "Mystiko",
    category: ["DAppL1"],
    intro: "Mystiko SDK is the zero knowledge (ZK) technology infrastructure for all blockchains and apps. Developers build on Mystiko SDK for applications that reduce costs, scale effortlessly, cross chains securely, and protect users onchain privacy (account balances, transaction histories, etc.)",
    date: "",
    round: "",
    status: "",
    website: "https://mystiko.network",
    twitter: "https://twitter.com/MystikoNetwork",
    icon: "icons/mystiko.png"
  },
  {
    id: "stage",
    name: "Stage",
    category: ["DApp"],
    intro: "",
    date: "",
    round: "",
    status: "",
    website: "",
    twitter: "",
    icon: "icons/stage.png"
  },
  {
    id: "puffer",
    name: "Puffer",
    category: ["Marketplace"],
    intro: "Puffer introduces Anti-Slashing Liquid Restaking, enabling users to earn rewards while decentralizing Ethereum.",
    date: "",
    round: "",
    status: "",
    website: "https://www.puffer.fi",
    twitter: "https://twitter.com/puffer_finance",
    icon: "icons/puffer.png"
  },
  {
    id: "victoriavr",
    name: "VictoriaVR",
    category: ["Metaverse"],
    intro: "Victoria VR is the first blockchain-based MMORPG in Virtual Reality with Realistic Graphics built on Unreal Engine, created and owned by its users.",
    date: "",
    round: "",
    status: "",
    website: "https://www.victoriavr.com",
    twitter: "https://twitter.com/VictoriaVRcom",
    icon: "icons/victoriavr.png"
  },
  {
    id: "beraborrow",
    name: "BeraBorrow",
    category: ["DeFi"],
    intro: "Beraborrow is a decentralised protocol at the forefront of the Berachain ecosystem based on the well known Liquity model on Ethereum",
    date: "",
    round: "",
    status: "",
    website: "https://beraborrow.com",
    twitter: "https://twitter.com/beraborrow",
    icon: "icons/beraborrow.png"
  },
  {
    id: "io-net",
    name: "IO Net",
    category: ["L1"],
    intro: "AI Compute-as-a-Currency, powered by $IO™ Internet of GPUs™ | Built on @solana",
    date: "",
    round: "",
    status: "",
    website: "https://io.net",
    twitter: "https://twitter.com/ionet_official",
    icon: "icons/io-net.png"
  },
  {
    id: "kryptomon",
    name: "Kryptomon",
    category: ["GameFi"],
    intro: "#KMON is buidling the BIGGEST true MMORPG video game experience in Web3.",
    date: "",
    round: "",
    status: "",
    website: "https://twitter.com",
    twitter: "https://twitter.com/KryptomonTeam",
    icon: "icons/kryptomon.png"
  },
  {
    id: "creo-engine",
    name: "Creo Engine",
    category: ["GameFi"],
    intro: "Creo Engine aims to revolutionize gaming by unifying diverse worlds into one dynamic hub, enhancing the Web3 gaming experience for all.",
    date: "",
    round: "",
    status: "",
    website: "https://creoengine.com/",
    twitter: "https://x.com/creo_engine",
    icon: "icons/creo-engine.png"
  },
  {
    id: "bravo-ready",
    name: "Bravo Ready",
    category: ["GameFi"],
    intro: "Bravo Ready builds games and products that fundamentally redefine what it means to be a Gamer. Bravo Ready is the parent company behind @BR1INFINITE, @PlayAptosArena, and others.",
    date: "",
    round: "",
    status: "",
    website: "https://bravoready.com/",
    twitter: "https://twitter.com/BRAVOREADYCORP",
    icon: "icons/bravo-ready.png"
  },
  {
    id: "coinweb",
    name: "CoinWeb",
    category: ["L2"],
    intro: "Coinweb introduces an L2 Consensus-Free Cross-Chain Protocol, transforming scalability and interoperability. Its decentralized platform allows effortless deployment of dApps across multiple blockchains.",
    date: "",
    round: "",
    status: "",
    website: "https://coinweb.io/",
    twitter: "https://twitter.com/CoinwebOfficial",
    icon: "icons/coinweb.png"
  },
  {
    id: "aethir-nodes",
    name: "Aethir Nodes",
    category: ["DApp"],
    intro: "Aethir Cloud is pioneering the development of Scalable Decentralized Cloud Infrastructure (DCI) specifically designed for gaming and AI applications.",
    date: "",
    round: "",
    status: "",
    website: "https://aethir.com/",
    twitter: "https://twitter.com/AethirCloud",
    icon: "icons/aethir-nodes.png"
  },
  {
    id: "fuel-on-blast",
    name: "Fuel on Blast",
    category: ["DApp"],
    intro: "FuelOnBlast offers a streamlined platform for creators to easily design and launch their own tokens, complete with customizable features. Tokens can be launched on the creator's chosen DEX, funded either through liquidity loans, which are repayable by taxes or direct payments, or by self-funding.",
    date: "",
    round: "",
    status: "",
    website: "https://fuelonblast.com/",
    twitter: "https://twitter.com/FuelOnBlast",
    icon: "icons/fuel-on-blast.png"
  },
  {
    id: "your",
    name: "YOUR",
    category: ["Marketplace"],
    intro: "AI Protocol optimized e-commerce integrated into Shopify’s 700M users built on Bitcoin and Solana",
    date: "",
    round: "",
    status: "",
    website: "https://bento.me",
    twitter: "https://twitter.com/yourtokens",
    icon: "icons/your.png"
  },
  {
    id: "alvara",
    name: "Alvara",
    category: ["Payment"],
    intro: "Utilizing the ERC-7621 to redefine #ETFs - Alvara is the gateway to the world of on-chain fund management.",
    date: "",
    round: "",
    status: "",
    website: "https://www.alvaraprotocol.io",
    twitter: "https://twitter.com/alvaraprotocol",
    icon: "icons/alvara.png"
  },
  {
    id: "sekuya",
    name: "Sekuya",
    category: ["Metaverse"],
    intro: "Sekuya is an epic fusion of AI, GameFi, and real-world assets in a Battle Arena adventure, incubated by @SingularityDAO.",
    date: "",
    round: "",
    status: "",
    website: "https://sekuya.io/",
    twitter: "https://twitter.com/sekuyaofficial",
    icon: "icons/sekuya.png"
  },
  {
    id: "lava-network",
    name: "Lava Network",
    category: ["DeFi"],
    intro: "Lava Network is a modular data access layer facilitating fast, reliable onboarding for rollups, currently available in test net.",
    date: "",
    round: "",
    status: "",
    website: "https://twitter.com",
    twitter: "https://twitter.com/lavanetxyz",
    icon: "icons/lava-network.png"
  },
  {
    id: "bitsmiley",
    name: "bitSmiley",
    category: ["BRC20"],
    intro: "A BTC-native stablecoin protocol, supported by initial funding from OKX Ventures and ABCDELabs, ushering in a new era of stability in the crypto space.",
    date: "",
    round: "",
    status: "",
    website: "https://bitsmiley.io/",
    twitter: "https://twitter.com/bitsmiley_labs",
    icon: "icons/bitsmiley.png"
  },
  {
    id: "solus",
    name: "Solus",
    category: ["DeFi"],
    intro: "Solus is the fastest growing, simple, engaging and low risk futures trading platform with over 72k+ active users on our app.",
    date: "",
    round: "",
    status: "",
    website: "https://solus.finance/",
    twitter: "https://twitter.com/SolusFinance",
    icon: "icons/solus.png"
  },
  {
    id: "aperture-finance",
    name: "Aperture Finance",
    category: ["DeFi"],
    intro: "ApertureSwap introduces groundbreaking LP management using intent-based architectures on Uniswap V3, offering a seamless experience. Custom-built decentralized exchange on Manta Network, redefining liquidity provision.",
    date: "",
    round: "",
    status: "",
    website: "https://app.aperture.finance/",
    twitter: "https://twitter.com/ApertureFinance",
    icon: "icons/aperture-finance.png"
  },
  {
    id: "darewise",
    name: "Darewise",
    category: ["Metaverse"],
    intro: "Darewise, a Metaverse technology company, is shaping the future of experiences on Bitcoin through projects like LifeBeyond and Sparks Ordinals. Proudly affiliated with Animoca Brands.",
    date: "",
    round: "",
    status: "",
    website: "https://darewise.com",
    twitter: "https://twitter.com/Darewise",
    icon: "icons/darewise.png"
  },
  {
    id: "beoble",
    name: "Beoble",
    category: ["SocialFi"],
    intro: "Beoble, the chat solution for Web3 enthusiasts, is supported by major backers including Animoca Brands, Samsung Next, HashKey Capital, and DCGco.",
    date: "",
    round: "",
    status: "",
    website: "https://beoble.io/",
    twitter: "https://twitter.com/beoble_official",
    icon: "icons/beoble.png"
  },
  {
    id: "canza-finance",
    name: "Canza Finance",
    category: ["DeFi"],
    intro: "Canza is building the world’s largest non-institutional-based financial system. By utilising Web3.0 and decentralised finance (DeFi) along with a robust network of experienced local money market players, Canza aims to distribute financial data and transaction-based services to the masses with it’s wide suite of products.",
    date: "",
    round: "",
    status: "",
    website: "https://canza.io/",
    twitter: "https://twitter.com/Canza_Finance",
    icon: "icons/canza-finance.png"
  },
  {
    id: "rtf-ready-to-fight",
    name: "RTF - Ready To Fight",
    category: ["GameFi"],
    intro: "RTF is the 1st blockchain boxing ecosystem aiming at the $10B boxing market and bridging 2B boxers & fans worldwide.",
    date: "",
    round: "",
    status: "",
    website: "https://rtf.social/",
    twitter: "https://twitter.com/RTFight_App",
    icon: "icons/rtf-ready-to-fight.png"
  },
  {
    id: "lynex",
    name: "Lynex",
    category: ["DeFi"],
    intro: "Lynex is a LST-focused DEX and liquidity marketplace on @LineaBuild, pioneering inclusive, advanced liquidity solutions through our ALM aggregation.",
    date: "",
    round: "",
    status: "",
    website: "https://lynex.fi/",
    twitter: "https://twitter.com/LynexFi",
    icon: "icons/lynex.png"
  },
  {
    id: "404aliens",
    name: "404Aliens",
    category: ["NFT"],
    intro: "",
    date: "",
    round: "",
    status: "",
    website: "",
    twitter: "#N/A",
    icon: "icons/404aliens.png"
  },
  {
    id: "lita-foundation",
    name: "Lita Foundation",
    category: ["Marketplace"],
    intro: "",
    date: "2024-02-14",
    round: "KOL Round",
    status: "Closed",
    website: "",
    twitter: "",
    icon: "icons/lita-foundation.png"
  },
  {
    id: "selfchain",
    name: "SelfChain",
    category: ["DeFi"],
    intro: "Modular Intent-Centric Access Layer 1 Blockchain and Keyless Wallet Infrastructure Service That Uses MPC-TSS/AA for Multi-Chain WEB3 Access.",
    date: "",
    round: "",
    status: "",
    website: "https://selfchain.xyz/",
    twitter: "https://twitter.com/selfchainxyz",
    icon: "icons/selfchain.png"
  },
  {
    id: "revolving-games",
    name: "Revolving Games",
    category: ["GameFi"],
    intro: "Revolving Games specialises in crafting innovative gaming experiences for Web3 and beyond, aiming to develop scalable, fully decentralized gaming solutions using cutting-edge technology.",
    date: "",
    round: "",
    status: "",
    website: "https://revolvinggames.com",
    twitter: "https://twitter.com/Revolving_Games",
    icon: "icons/revolving-games.png"
  },
  {
    id: "ordibank",
    name: "OrdiBank",
    category: ["L1"],
    intro: "A Bitcoin L1 Money Market Protocol for BRC-20 & Atomical Token Standards, facilitating seamless Borrowing/Lending.",
    date: "",
    round: "",
    status: "",
    website: "https://ordibank.org/",
    twitter: "https://twitter.com/Ordibank",
    icon: "icons/ordibank.png"
  },
  {
    id: "humanity-protocol",
    name: "Humanity Protocol",
    category: ["L1"],
    intro: "Building the future, one human at a time !",
    date: "",
    round: "",
    status: "",
    website: "https://linktr.ee",
    twitter: "https://twitter.com/HmntyProtocol",
    icon: "icons/humanity-protocol.png"
  },
  {
    id: "gt-protocol",
    name: "GT Protocol",
    category: ["Marketplace"],
    intro: "GT Protocol offers an intuitive non-custodial crypto investment experience guided by blockchain AI execution interface. Profitable strategies featuring controllable risk levels, along with a transparent and traceable history of every deal. Access to crypto investments across DeFi, CeFi, and NFT markets.",
    date: "",
    round: "",
    status: "",
    website: "https://www.gt-protocol.io",
    twitter: "https://twitter.com/gt_protocol",
    icon: "icons/gt-protocol.png"
  },
  {
    id: "light-link",
    name: "Light Link",
    category: ["DApp"],
    intro: "LightLink is an Ethereum L2 blockchain that lets dApps and enterprises offer users instant, gasless transactions. Top 10 in transaction volume among rollups.",
    date: "",
    round: "",
    status: "",
    website: "https://lightlink.io/",
    twitter: "https://twitter.com/LightLinkChain",
    icon: "icons/light-link.png"
  },
  {
    id: "particle-network",
    name: "Particle Network",
    category: ["L1"],
    intro: "The Modular L1 Powering Chain Abstraction",
    date: "",
    round: "",
    status: "",
    website: "https://particle.network/",
    twitter: "https://twitter.com/ParticleNtwrk",
    icon: "icons/particle-network.png"
  },
  {
    id: "codex",
    name: "Codex",
    category: ["L1"],
    intro: "CODEX empowers all crypto enthusiasts, enabling them to utilize their digital currency to receive a fiat counterpart, buying gift vouchers, social media interaction, accounts, and much more.",
    date: "",
    round: "",
    status: "",
    website: "https://codextoken.com",
    twitter: "https://twitter.com/codex_token",
    icon: "icons/codex.png"
  },
  {
    id: "libera",
    name: "Libera",
    category: ["Payment"],
    intro: "",
    date: "",
    round: "",
    status: "",
    website: "",
    twitter: "",
    icon: "icons/libera.png"
  },
  {
    id: "flash-protocol",
    name: "Flash protocol",
    category: ["L1DeFi"],
    intro: "Flash Protocol, fueled by #Taproot, emerges as Bitcoin's premier NFT issuance platform, propelling GameFi, AI, and Meme culture forward.",
    date: "",
    round: "",
    status: "",
    website: "https://flashprotocol.xyz",
    twitter: "https://twitter.com/flashprotocol",
    icon: "icons/flash-protocol.png"
  },
  {
    id: "iconx",
    name: "IconX",
    category: ["GameFi"],
    intro: "IconX World creates an ecosystem where racers and sponsors profit from Compete-and-Earn.",
    date: "",
    round: "",
    status: "",
    website: "https://www.iconx.world",
    twitter: "https://twitter.com/IconxWorld",
    icon: "icons/iconx.png"
  },
  {
    id: "entangle",
    name: "Entangle",
    category: ["DApp"],
    intro: "EntangleFi is pioneering an omnichain blockchain Infrastructure consisting of core primitives and tools unifying the blockchain ecosystem whilst delivering universal Web2 or Web3 data to smart contracts on any chain.",
    date: "",
    round: "",
    status: "",
    website: "https://entangle.fi",
    twitter: "https://twitter.com/Entanglefi",
    icon: "icons/entangle.png"
  },
  {
    id: "sparknet",
    name: "SparkNet",
    category: ["Marketplace"],
    intro: "SparqNet is a meta-network that provides tools and services for a network of deployable blockchains capable of up to 400k TPS each, programmable in any language with infrastructure enabled by Avalanche, and open to any protocol through the on-chain trustless and distributed bridge.",
    date: "",
    round: "",
    status: "",
    website: "https://sparq.network",
    twitter: "https://twitter.com/SparqNet",
    icon: "icons/sparknet.png"
  },
  {
    id: "brcport",
    name: "BRCPort",
    category: ["Payment"],
    intro: "BRCport is constructing Bitcoin infrastructure, offering a versatile hub for bridges, launchpads, cross-chain swaps, NFT minting, and more",
    date: "",
    round: "",
    status: "",
    website: "https://bento.me",
    twitter: "https://twitter.com/BrcPort",
    icon: "icons/brcport.png"
  },
  {
    id: "niburu-chain",
    name: "Niburu Chain",
    category: ["DeFi"],
    intro: "Nibiru Chain, the Web3 hub, is leading the transition into the future of finance. It operates as an L1 blockchain, driving a smart contract hub with DeFi, RWAs, and beyond. Explore more at https://nibiru.fi.",
    date: "",
    round: "",
    status: "",
    website: "https://nibiru.fi",
    twitter: "https://twitter.com/NibiruChain",
    icon: "icons/niburu-chain.png"
  },
  {
    id: "edu3labs",
    name: "Edu3Labs",
    category: ["NFT"],
    intro: "Edu3Labs pioneers the reinvention of education with Web3, utilising the power of AI and blockchain for transformative learning experiences.",
    date: "",
    round: "",
    status: "",
    website: "https://edu3labs.com",
    twitter: "https://twitter.com/Edu3Labs",
    icon: "icons/edu3labs.png"
  },
  {
    id: "minterest",
    name: "Minterest",
    category: ["DeFi"],
    intro: "Minterest is a Cross-chain DeFi Lending protocol that redistributes 100% of value captured back to users.",
    date: "",
    round: "",
    status: "",
    website: "https://minterest.com",
    twitter: "https://twitter.com/Minterest",
    icon: "icons/minterest.png"
  },
  {
    id: "devomon",
    name: "Devomon",
    category: ["GameFi"],
    intro: "Devomon, a prominent WEB3 anime brand, transcends traditional gaming realms. Offering immersive games, unique merchandise, and an extensive universe, it's a testament to anime culture's impact.",
    date: "",
    round: "",
    status: "",
    website: "https://www.devomon.io",
    twitter: "https://twitter.com/OfficialDevomon",
    icon: "icons/devomon.png"
  },
  {
    id: "ordify",
    name: "Ordify",
    category: ["Marketplace"],
    intro: "Ordify introduces a suite of products, crafted to enhance investment experiences across diverse chains. From launchpads to bridges to wallets, unlock opportunities in decentralized finance.",
    date: "",
    round: "",
    status: "",
    website: "https://ordify.world",
    twitter: "https://twitter.com/OrdifyWorld",
    icon: "icons/ordify.png"
  },
  {
    id: "overlay",
    name: "Overlay",
    category: ["Marketplace"],
    intro: "Overlay is built from the ground up with OV, a cryptocurrency that longs/shorts DeFi data streams and much, much more.",
    date: "",
    round: "",
    status: "",
    website: "https://overlay.market",
    twitter: "https://x.com/OverlayProtocol",
    icon: "icons/overlay.png"
  },
  {
    id: "dechat",
    name: "Dechat",
    category: ["SocialFi"],
    intro: "Dechat is an open, secure web3 communications protocol that powers decentralized user interactions.",
    date: "",
    round: "",
    status: "",
    website: "https://www.dechat.io",
    twitter: "https://twitter.com/dechat_io",
    icon: "icons/dechat.png"
  },
  {
    id: "octavia",
    name: "Octavia",
    category: ["AI"],
    intro: "Octavia is a web3-based autonomous assistant powered by the $VIA token.",
    date: "",
    round: "",
    status: "",
    website: "https://octavia.one",
    twitter: "https://twitter.com/OctaviaToken",
    icon: "icons/octavia.png"
  },
  {
    id: "farcana",
    name: "Farcana",
    category: ["GameFi"],
    intro: "Farcana is a multiplayer arena hero shooter powered by a Web3 economy.",
    date: "",
    round: "",
    status: "",
    website: "https://farcana.com/",
    twitter: "https://twitter.com/FarcanaOfficial",
    icon: "icons/farcana.png"
  },
  {
    id: "sharkyfi",
    name: "SharkyFi",
    category: ["NFT"],
    intro: "FIRST Escrow-less NFT lending protocol! LARGEST on Solana Lend & Borrow $SOL instantly against your NFTs.",
    date: "",
    round: "",
    status: "",
    website: "https://sharky.fi/",
    twitter: "https://twitter.com/SharkyFi",
    icon: "icons/sharkyfi.png"
  },
  {
    id: "blocklords",
    name: "Blocklords",
    category: ["GameFi"],
    intro: "The most ambitious strategy game of our age.",
    date: "",
    round: "",
    status: "",
    website: "https://blocklords.com",
    twitter: "https://twitter.com/BLOCKLORDS",
    icon: "icons/blocklords.png"
  },
  {
    id: "tap-protocol",
    name: "Tap Protocol",
    category: ["BRC20DApp"],
    intro: "Tap is an OrdFi enabling protocol for Bitcoin Ordinals created by",
    date: "",
    round: "",
    status: "",
    website: "https://trac.network/",
    twitter: "https://twitter.com/tap_protocol",
    icon: "icons/tap-protocol.png"
  },
  {
    id: "magic-square",
    name: "Magic Square",
    category: ["Marketplace"],
    intro: "The Web3 App Store",
    date: "",
    round: "",
    status: "",
    website: "https://magic.store/",
    twitter: "https://twitter.com/MagicSquareio",
    icon: "icons/magic-square.png"
  },
  {
    id: "pec-land",
    name: "Pec Land",
    category: ["GameFi"],
    intro: "",
    date: "",
    round: "",
    status: "",
    website: "https://pecland.xyz",
    twitter: "https://twitter.com/PEClandOfficial",
    icon: "icons/pec-land.png"
  },
  {
    id: "forward-protocol",
    name: "Forward Protocol",
    category: ["DeFi"],
    intro: "The gateway to #Blockchain #adoption. WordPress for #Web3. Customizable, no-code, drag & drop interface.",
    date: "",
    round: "",
    status: "",
    website: "https://forwardprotocol.io/",
    twitter: "https://twitter.com/ForwardProtocol",
    icon: "icons/forward-protocol.png"
  },
  {
    id: "sats-bridge",
    name: "Sats Bridge",
    category: ["BRC20"],
    intro: "Bridging Inscriptions/BRC20 on multiple chains.",
    date: "",
    round: "",
    status: "",
    website: "https://satsbridge.io/",
    twitter: "https://twitter.com/SatsBridge_io",
    icon: "icons/sats-bridge.png"
  },
  {
    id: "gpt-protocol",
    name: "GPT Protocol",
    category: ["AI"],
    intro: "Censorship-Resistant Intelligence",
    date: "",
    round: "",
    status: "",
    website: "https://gptprotocol.org/",
    twitter: "https://twitter.com/gpt_protocol",
    icon: "icons/gpt-protocol.png"
  },
  {
    id: "gamegpt-duel",
    name: "GameGPT Duel",
    category: ["NFT"],
    intro: "AI Driven Game Engine - $DUEL - NFT mint coming Soon",
    date: "",
    round: "",
    status: "",
    website: "https://bento.me/gamegpt",
    twitter: "https://twitter.com/Gamegptofficial",
    icon: "icons/gamegpt-duel.png"
  },
  {
    id: "brcstarter",
    name: "BRCStarter",
    category: ["BRC20"],
    intro: "#BRCStarter is a BRC-20 focused launchpad that aims to accelerate the adoption of #BRC20 projects.",
    date: "",
    round: "",
    status: "",
    website: "https://brcstarter.io/",
    twitter: "https://twitter.com/BRCStarteroff",
    icon: "icons/brcstarter.png"
  },
  {
    id: "metaxseed",
    name: "MetaXseed",
    category: ["L1"],
    intro: "Layer 1 with large library of Mobile & PC games. Seamless onboarding and sustainable revenues",
    date: "",
    round: "",
    status: "",
    website: "https://metaxseed.io/",
    twitter: "https://twitter.com/metaxseed",
    icon: "icons/metaxseed.png"
  },
  {
    id: "port3",
    name: "Port3",
    category: ["SocialFi"],
    intro: "Incentivizing Intelligence in Trustless Networks ~ DeCalc/DePin | @Port3BQL | @SoPadPort3 | @soquest_xyz",
    date: "",
    round: "",
    status: "",
    website: "https://port3.io/",
    twitter: "https://twitter.com/Port3Network",
    icon: "icons/port3.png"
  },
  {
    id: "niburu-chain",
    name: "Niburu Chain",
    category: ["DeFi"],
    intro: "The Web3 hub ushering in the next era of money. Nibiru is an L1 blockchain powering a smart contract hub with DeFi, RWAs, and more",
    date: "",
    round: "",
    status: "",
    website: "https://niburu.fi/",
    twitter: "https://twitter.com/NibiruChain",
    icon: "icons/niburu-chain.png"
  },
  {
    id: "befilabs",
    name: "BefiLabs",
    category: ["BRC20"],
    intro: "₿RC20 Trading Terminal functional with your favorite crypto wallets",
    date: "",
    round: "",
    status: "",
    website: "https://befilabs.com/",
    twitter: "https://twitter.com/BefiLabs",
    icon: "icons/befilabs.png"
  },
  {
    id: "ordz-games",
    name: "ORDZ Games",
    category: ["BRC20"],
    intro: "1st Gaming Project on #Bitcoin (launched Mar 22) Powered by $ORDG, 1st BRC-20 token with utility (inscribed Mar 15) http://ordz.games",
    date: "",
    round: "",
    status: "",
    website: "https://ordz.games/",
    twitter: "https://twitter.com/OrdzGames",
    icon: "icons/ordz-games.png"
  },
  {
    id: "animalia",
    name: "Animalia",
    category: ["GameFiNFT"],
    intro: "Animalia is an independent f2p online NFT trading card game featuring crypto-inspired meme creatures.",
    date: "",
    round: "",
    status: "",
    website: "https://animalia.games/",
    twitter: "https://twitter.com/Animalia_games",
    icon: "icons/animalia.png"
  },
  {
    id: "dotins",
    name: "DotIns",
    category: ["DApp"],
    intro: "Introducing the first comprehensive and interactive @Polkadot & @kusamanetwork",
    date: "",
    round: "",
    status: "",
    website: "https://dotinsights.xyz",
    twitter: "https://twitter.com/dotinsights_xyz",
    icon: "icons/dotins.png"
  },
  {
    id: "playbux",
    name: "Playbux",
    category: ["GameFi"],
    intro: "The largest web3 entertainment platform in the world. Backed by Binance Labs | VISA Accelerator 2023 support@playbux.co",
    date: "",
    round: "",
    status: "",
    website: "https://www.playbux.co",
    twitter: "https://twitter.com/playbuxco",
    icon: "icons/playbux.png"
  },
  {
    id: "teleport-dao",
    name: "Teleport DAO",
    category: ["DApp"],
    intro: "Build cross-chain Bitcoin apps http://teleportdao.xyz",
    date: "",
    round: "",
    status: "",
    website: "https://teleportdao.xyz",
    twitter: "https://twitter.com/Teleport_DAO",
    icon: "icons/teleport-dao.png"
  },
  {
    id: "mixmob",
    name: "MixMob",
    category: ["GameFi"],
    intro: "World’s 1st card strategy racing game. Race . Win . Stake . From the team behind FIFA & Halo. Backed by @cryptohayes @darrenlautf @asvanevik @solana",
    date: "",
    round: "",
    status: "",
    website: "https://mixmob-v3.webflow.io",
    twitter: "https://twitter.com/MixMobOrigin",
    icon: "icons/mixmob.png"
  },
  {
    id: "unirouter",
    name: "UniRouter",
    category: ["DeFi"],
    intro: "Empower #Bitcoin with Next-gen Liquid Staking",
    date: "",
    round: "",
    status: "",
    website: "https://unirouter.io/",
    twitter: "https://twitter.com/UniRouterBTC",
    icon: "icons/unirouter.png"
  },
  {
    id: "yellow",
    name: "Yellow",
    category: ["DeFi"],
    intro: "Web3 #blockchain products & services ecosystem | Building next-gen #DeFi experience for exchanges, brokers & traders",
    date: "",
    round: "",
    status: "",
    website: "https://yellow.org/",
    twitter: "https://twitter.com/Yellow",
    icon: "icons/yellow.png"
  },
  {
    id: "soul-society",
    name: "Soul Society",
    category: ["SocialFi"],
    intro: "SoulSociety is a Web3 social service that utilizes SBTs",
    date: "",
    round: "",
    status: "",
    website: "https://soulsociety.gg",
    twitter: "https://twitter.com/SoulSociety_HON",
    icon: "icons/soul-society.png"
  },
  {
    id: "grapes",
    name: "Grapes",
    category: ["GameFi"],
    intro: "The home of Grapes and $GRAPE Coin. Backed by @animocabrands",
    date: "",
    round: "",
    status: "",
    website: "https://www.joingrapes.com",
    twitter: "https://twitter.com/JoinGrapes",
    icon: "icons/grapes.png"
  },
  {
    id: "solana-gun",
    name: "Solana Gun",
    category: ["MarketplaceNFT"],
    intro: "",
    date: "",
    round: "",
    status: "",
    website: "",
    twitter: "",
    icon: "icons/solana-gun.png"
  },
  {
    id: "exverse",
    name: "ExVerse",
    category: ["GameFi"],
    intro: "Powered by @immutable. Incubated by @SeedifyFund & @KCLabsOfficial. #AI-powered Revolutionary",
    date: "",
    round: "",
    status: "",
    website: "https://exv.io/",
    twitter: "https://twitter.com/exverse_io",
    icon: "icons/exverse.png"
  },
  {
    id: "aether-games",
    name: "Aether Games",
    category: ["GameFi"],
    intro: "Aether Games is a transmedia development studio that creates immersive gaming and entertainment experiences for both web2 and web3 @AetherTCG @AetherSaga",
    date: "",
    round: "",
    status: "",
    website: "https://aethergames.io/",
    twitter: "https://twitter.com/AetherGamesInc",
    icon: "icons/aether-games.png"
  },
  {
    id: "betroyale",
    name: "BetRoyale",
    category: ["GameFi"],
    intro: "The King’s Casino Old Money Industry, New Age #GambleFi Project",
    date: "",
    round: "",
    status: "",
    website: "https://betroyale.io/",
    twitter: "https://twitter.com/betroyale_io",
    icon: "icons/betroyale.png"
  },
  {
    id: "bloodloop",
    name: "BloodLoop",
    category: ["GameFi"],
    intro: "A 5v5 tactical Hero-Shooter game, integrated with blockchain.",
    date: "",
    round: "",
    status: "",
    website: "https://bloodloop.com/",
    twitter: "https://twitter.com/BloodLoopGAME",
    icon: "icons/bloodloop.png"
  },
  {
    id: "mypethooligan",
    name: "MyPetHooligan",
    category: ["GameFi"],
    intro: "Got karrats? An interactive entertainment experience from @amgistudios. Free-to-play, early access game out now!..",
    date: "",
    round: "",
    status: "",
    website: "https://mypethooligan.com/",
    twitter: "https://twitter.com/mypethooligan",
    icon: "icons/mypethooligan.png"
  },
  {
    id: "metacard",
    name: "MetaCard",
    category: ["Marketplace"],
    intro: "Elevate the way you gift & connect! Secure, no-code gift card platform bridging tradition, blockchain tech & DeFi.",
    date: "",
    round: "",
    status: "",
    website: "https://metacard.gift/",
    twitter: "https://twitter.com/gift_metacard",
    icon: "icons/metacard.png"
  },
  {
    id: "readygg",
    name: "ReadyGG",
    category: ["GameFi"],
    intro: "Making infrastructure for the Web3 Games & Dev creator economy⁣ Join the Ecosystem",
    date: "",
    round: "",
    status: "",
    website: "https://ready.gg/",
    twitter: "https://twitter.com/TheReadyGames",
    icon: "icons/readygg.png"
  },
  {
    id: "chirp",
    name: "Chirp",
    category: ["DePIN"],
    intro: "Chirp is a #DePIN telecommunications network harnesing the power of #blockchain. #IoT #Voice #broadband.",
    date: "",
    round: "",
    status: "",
    website: "https://chirptoken.io/",
    twitter: "https://twitter.com/ChirpDeWi",
    icon: "icons/chirp.png"
  },
  {
    id: "garbage",
    name: "Garbage",
    category: ["NFTMarketplace"],
    intro: "THE NEW HUB FOR MEMECOINS. This is not financial advice, this is $GARBAGE",
    date: "",
    round: "",
    status: "",
    website: "https://buygarbage.io/",
    twitter: "https://twitter.com/buygarbage",
    icon: "icons/garbage.png"
  },
  {
    id: "sect-bot",
    name: "Sect Bot",
    category: ["AI"],
    intro: "Revolutionary tracking bot that transforms crypto Discord & Telegram trading into a rewarding competition.",
    date: "",
    round: "",
    status: "",
    website: "https://sectbot.com",
    twitter: "https://twitter.com/thesectbot",
    icon: "icons/sect-bot.png"
  },
  {
    id: "gpu-net",
    name: "GPU Net",
    category: ["DApp"],
    intro: "$GPU Trustless compute. Use GPUs on http://App.gpu.net, Layer1 Proof of Compute, Node launch shortly",
    date: "",
    round: "",
    status: "",
    website: "https://gpu.net/",
    twitter: "https://twitter.com/gpunet",
    icon: "icons/gpu-net.png"
  },
  {
    id: "dyordex",
    name: "DyorDex",
    category: ["DeFiDApp"],
    intro: "Your Onchain Command Center Coming this year!",
    date: "",
    round: "",
    status: "",
    website: "https://DyorDex.com/",
    twitter: "https://DyorDex.com/",
    icon: "icons/dyordex.png"
  },
  {
    id: "data-ownership-protocol",
    name: "Data Ownership Protocol",
    category: ["L2Payment"],
    intro: "Bringing selective transparency to Ethereum. Using zero-knowledge proofs, DOP allows you to decide what crypto assets and transactions you wish to make public.",
    date: "",
    round: "",
    status: "",
    website: "https://dop.org/",
    twitter: "https://twitter.com/dop_org",
    icon: "icons/data-ownership-protocol.png"
  },
  {
    id: "raiinmaker",
    name: "Raiinmaker",
    category: ["AI"],
    intro: "DePIN Validator Powered by the Coiin Network",
    date: "",
    round: "",
    status: "",
    website: "https://rainmaker.com/",
    twitter: "https://twitter.com/Raiinmakerapp",
    icon: "icons/raiinmaker.png"
  },
  {
    id: "momentum",
    name: "Momentum",
    category: ["NFT"],
    intro: "Momentum is a curated group of like-minded traders that share ideas, information and alpha.",
    date: "",
    round: "",
    status: "",
    website: "https://momentum.lol/",
    twitter: "https://twitter.com/MomentumNFT_",
    icon: "icons/momentum.png"
  },
  {
    id: "bitscrunch",
    name: "BitsCrunch",
    category: ["NFT"],
    intro: "AI enhanced Decentralized Data Analytics & Forensics Protocol",
    date: "",
    round: "",
    status: "",
    website: "https://bitscrunch.com/",
    twitter: "https://twitter.com/bitsCrunch",
    icon: "icons/bitscrunch.png"
  },
  {
    id: "plexus",
    name: "Plexus",
    category: ["DApp"],
    intro: "The best cross-chain liquidity aggregator and middleware infra. All chains, all tokens, and the optimal swap with just one click and one API.",
    date: "",
    round: "",
    status: "",
    website: "https://plexus.app/",
    twitter: "https://twitter.com/plexus_fi",
    icon: "icons/plexus.png"
  },
  {
    id: "workx",
    name: "WorkX",
    category: ["AIMarketplace"],
    intro: "Building Work X: the first decentralized job economy empowering both talent and employers without commercial fees",
    date: "",
    round: "",
    status: "",
    website: "https://work-x.io/",
    twitter: "https://twitter.com/WorkX_official",
    icon: "icons/workx.png"
  },
  {
    id: "serenity-shield",
    name: "Serenity Shield",
    category: ["DApp"],
    intro: "Discover #StrongBox®: Secure, Decentralized, Private Data Storage and Inheritance Solutions using Blockchain Technology.",
    date: "",
    round: "",
    status: "",
    website: "https://serenityshield.io/",
    twitter: "https://twitter.com/SerenityShield_",
    icon: "icons/serenity-shield.png"
  },
  {
    id: "famecoin",
    name: "FameCoin",
    category: ["DApp"],
    intro: "The currency of influencers A platform which allows us to collect and bet on those who inspire us the most!",
    date: "",
    round: "",
    status: "",
    website: "https://famecoin.io/",
    twitter: "https://twitter.com/Famecoin_dapp",
    icon: "icons/famecoin.png"
  },
  {
    id: "darkfi",
    name: "DarkFi",
    category: ["L1"],
    intro: "Let there be dark ⛛",
    date: "",
    round: "",
    status: "",
    website: "https://dark.fi",
    twitter: "https://twitter.com/DarkFiSquad",
    icon: "icons/darkfi.png"
  },
  {
    id: "databas3",
    name: "Databas3",
    category: ["Incubator"],
    intro: "We help founders make it in web3. Biggest database of investors, service providers and knowledge.",
    date: "",
    round: "",
    status: "",
    website: "https://databas3.net/",
    twitter: "https://twitter.com/Databas3Net",
    icon: "icons/databas3.png"
  },
  {
    id: "repulik-gg",
    name: "RepuliK GG",
    category: ["SocialFiDApp"],
    intro: "$RPK is web3stagram. Social media, reimagined. A revolution to bring ownership and voting rights to the community you create RepubliK = Power Back to The People",
    date: "",
    round: "",
    status: "",
    website: "https://republik.gg/",
    twitter: "https://twitter.com/RepubliK_GG",
    icon: "icons/repulik-gg.png"
  },
  {
    id: "vanar",
    name: "VANAR",
    category: ["L1"],
    intro: "The groundbreaking blockchain Vanar offers a carbon-neutral, high-speed & low-cost L1 chain designed for entertainment & mainstream.",
    date: "",
    round: "",
    status: "",
    website: "https://vanarchain.com/",
    twitter: "https://twitter.com/Vanarchain",
    icon: "icons/vanar.png"
  },
  {
    id: "shrapnel",
    name: "Shrapnel",
    category: ["GameFi"],
    intro: "The 1st moddable extraction shooter game, built by a unique team of BAFTA & Emmy Award-winning talent, using UE5 & blockchain.",
    date: "",
    round: "",
    status: "",
    website: "https://www.shrapnel.com",
    twitter: "https://twitter.com/playSHRAPNEL",
    icon: "icons/shrapnel.png"
  },
  {
    id: "supra-oracles",
    name: "Supra Oracles",
    category: ["DAppDeFi"],
    intro: "Upgrade your smart contracts with accurate, secure, stable, and blazing fast data feeds from DORA — Supra's novel decentralized cross-chain oracle solution.",
    date: "",
    round: "",
    status: "",
    website: "https://supra.com/",
    twitter: "https://twitter.com/SupraOracles",
    icon: "icons/supra-oracles.png"
  },
  {
    id: "xnova",
    name: "Xnova",
    category: ["NFT"],
    intro: "Xnova is a highly exploratory WEB3 experiment.",
    date: "",
    round: "",
    status: "",
    website: "https://xnovalab.org/",
    twitter: "https://twitter.com/xnovalab",
    icon: "icons/xnova.png"
  },
  {
    id: "chappyz",
    name: "Chappyz",
    category: ["AI"],
    intro: "Chappyz is an AI-powered, community engagement Plug N play Protocol.",
    date: "",
    round: "",
    status: "",
    website: "https://chapped.com/",
    twitter: "https://twitter.com/Chappyzcom",
    icon: "icons/chappyz.png"
  },
  {
    id: "weway",
    name: "WeWay",
    category: ["L1DeFi"],
    intro: "Dive into top Web3 projects, earn while you explore, and snag rewards every step of your journey.",
    date: "",
    round: "",
    status: "",
    website: "https://bento.me",
    twitter: "https://twitter.com/WeWay_io",
    icon: "icons/weway.png"
  },
  {
    id: "zogi-labs",
    name: "Zogi Labs",
    category: ["GameFi"],
    intro: "The 1st Decentralized Gaming-As-A Service Product | MMORPG | Battle Royal | No-Code Map Building",
    date: "",
    round: "",
    status: "",
    website: "https://zogilabs.io/",
    twitter: "https://twitter.com/ZogiLabs",
    icon: "icons/zogi-labs.png"
  },
  {
    id: "openfabric-ai",
    name: "OpenFabric AI",
    category: ["AI"],
    intro: "Openfabric lets anyone create, share, and monetize AI services at scale.",
    date: "",
    round: "",
    status: "",
    website: "https://openfabric.io/",
    twitter: "https://twitter.com/openfabricai",
    icon: "icons/openfabric-ai.png"
  },
  {
    id: "plenafinance",
    name: "PlenaFinance",
    category: ["DApp"],
    intro: "The First #Crypto Super App Powered By #AccountAbstraction | Non-Custodial | Buy 100,000+ Crypto at Best Rates",
    date: "",
    round: "",
    status: "",
    website: "https://plena.finance/",
    twitter: "https://twitter.com/PlenaFinance",
    icon: "icons/plenafinance.png"
  },
  {
    id: "phaver",
    name: "Phaver",
    category: ["SocialFi"],
    intro: "The largest web3 social app powered by @LensProtocol",
    date: "",
    round: "",
    status: "",
    website: "https://phaver.com/",
    twitter: "https://twitter.com/phaverapp",
    icon: "icons/phaver.png"
  },
  {
    id: "cyber-arena",
    name: "Cyber Arena",
    category: ["NFT"],
    intro: "Cyber Arena Augmented Reality $CAT | The 1st real-time online multiplayer AR & VR fighting game",
    date: "",
    round: "",
    status: "",
    website: "https://cyber-arena.co/",
    twitter: "https://twitter.com/CyberArena_NFT",
    icon: "icons/cyber-arena.png"
  },
  {
    id: "inspect",
    name: "Inspect",
    category: ["L2"],
    intro: "Official account of the Inspect DAO",
    date: "",
    round: "",
    status: "",
    website: "https://inspect.xyz/",
    twitter: "https://twitter.com/nftinspect",
    icon: "icons/inspect.png"
  },
  {
    id: "rektgame",
    name: "REKTGame",
    category: ["L2NFT"],
    intro: "ALL ROADS LEAD TO $REKT Game",
    date: "",
    round: "",
    status: "",
    website: "https://rekt.game",
    twitter: "https://twitter.com/rekt",
    icon: "icons/rektgame.png"
  },
  {
    id: "virtual-versions",
    name: "Virtual Versions",
    category: ["SocialFi"],
    intro: "We enable users to own their data and social identity, with a decentralized AI digital twin you can use anywhere.",
    date: "",
    round: "",
    status: "",
    website: "https://www.virtualversions.xyz",
    twitter: "https://twitter.com/virtualversions",
    icon: "icons/virtual-versions.png"
  },
  {
    id: "manilla-finance",
    name: "Manilla Finance",
    category: ["DeFi"],
    intro: "Manilla is an innovative & scalable CEDEFI project bridging conventional fintech services to the Blockchain & enabling bills settlement in Cryptocurrency",
    date: "",
    round: "",
    status: "",
    website: "https://manilla.finance/",
    twitter: "https://twitter.com/manilla_finance",
    icon: "icons/manilla-finance.png"
  },
  {
    id: "klubcoin",
    name: "KlubCoin",
    category: ["L2"],
    intro: "The lifestyle crypto token for party people & the electronic music world",
    date: "",
    round: "",
    status: "",
    website: "https://klubcoin.net",
    twitter: "https://twitter.com/KlubCoin",
    icon: "icons/klubcoin.png"
  },
  {
    id: "pyme-dao",
    name: "Pyme DAO",
    category: ["Incubator"],
    intro: "",
    date: "",
    round: "",
    status: "",
    website: "https://pymedao.com/",
    twitter: "https://twitter.com/PymeDAO",
    icon: "icons/pyme-dao.png"
  },
  {
    id: "altlayer",
    name: "AltLayer",
    category: ["L2"],
    intro: "Accelerate @ethereum with restaked rollups.",
    date: "",
    round: "",
    status: "",
    website: "https://altlayer.io/",
    twitter: "https://twitter.com/alt_layer",
    icon: "icons/altlayer.png"
  },
  {
    id: "kryptonite",
    name: "Kryptonite",
    category: ["DeFi"],
    intro: "Liquid Staking with Bera tokenomics on Sei and Nibiru. Official Partner of @SeiNetwork @NibiruChain",
    date: "",
    round: "",
    status: "",
    website: "https://krypto.finance/",
    twitter: "https://twitter.com/Kryptonite_fi",
    icon: "icons/kryptonite.png"
  },
  {
    id: "prasaga",
    name: "Prasaga",
    category: ["L1"],
    intro: "PraSaga is building the next generation Single Layer blockchain and is a Swiss Foundation.",
    date: "",
    round: "",
    status: "",
    website: "https://presage.com/",
    twitter: "https://twitter.com/prasagaofficial",
    icon: "icons/prasaga.png"
  },
  {
    id: "chainflip",
    name: "ChainFlip",
    category: ["DeFi"],
    intro: "A game changing native cross-chain AMM. Low slippage, Decentralised composable & permissionless.",
    date: "",
    round: "",
    status: "",
    website: "https://chainflip.io/",
    twitter: "https://twitter.com/Chainflip",
    icon: "icons/chainflip.png"
  },
  {
    id: "patex",
    name: "Patex",
    category: ["L2DeFi"],
    intro: "Patex is the first blockchain ecosystem targeting Latin America, a region with 670M+ people and a $5.5 trillion GDP",
    date: "",
    round: "",
    status: "",
    website: "https://patex.io/",
    twitter: "https://twitter.com/patex_ecosystem",
    icon: "icons/patex.png"
  },
  {
    id: "cashcrunch",
    name: "CashCrunch",
    category: ["GameFi"],
    intro: "Helping future generations learn the value of money and make smarter money decisions through gamification for ages 5 to 21 #finlit",
    date: "",
    round: "",
    status: "",
    website: "https://cashcrunchgames.com/",
    twitter: "https://twitter.com/CashCrunchGames",
    icon: "icons/cashcrunch.png"
  },
  {
    id: "bsx",
    name: "BSX",
    category: ["DeFi"],
    intro: "The Fastest Non-custodial Decentralized Exchange",
    date: "",
    round: "",
    status: "",
    website: "https://twitter.com",
    twitter: "https://twitter.com/bsx_labs",
    icon: "icons/bsx.png"
  },
  {
    id: "paysenger",
    name: "Paysenger",
    category: ["L2"],
    intro: "$EGO is a native token of http://Paysenger.com: top-1 app for creators!",
    date: "",
    round: "",
    status: "",
    website: "https://twitter.com",
    twitter: "https://twitter.com/Ego_Paysenger",
    icon: "icons/paysenger.png"
  },
  {
    id: "gensyn-ai",
    name: "Gensyn AI",
    category: ["AI"],
    intro: "the gensyn network unites all of the world's compute into a global machine learning cluster, usable by anyone at any time",
    date: "",
    round: "",
    status: "",
    website: "https://twitter.com",
    twitter: "https://twitter.com/gensynai",
    icon: "icons/gensyn-ai.png"
  },
  {
    id: "brickken",
    name: "Brickken",
    category: ["DeFi"],
    intro: "Create, sell, and manage digital assets—tokenization made simple. Real World Assets (RWA)",
    date: "",
    round: "",
    status: "",
    website: "https://brickken.com",
    twitter: "https://twitter.com/Brickken",
    icon: "icons/brickken.png"
  },
  {
    id: "axen",
    name: "Axen",
    category: ["AI"],
    intro: "Axen builds AI products that enable anyone to easily find & invest in new crypto assets before they moon",
    date: "",
    round: "",
    status: "",
    website: "https://axenai.com/",
    twitter: "https://twitter.com/Axenlabs",
    icon: "icons/axen.png"
  },
  {
    id: "blockhaus",
    name: "Blockhaus",
    category: ["DApp"],
    intro: "Exploring the limits of on-chain generation.",
    date: "",
    round: "",
    status: "",
    website: "https://blockhaus.uk/",
    twitter: "https://twitter.com/BlockhausNFT",
    icon: "icons/blockhaus.png"
  },
  {
    id: "gpt-guru",
    name: "GPT Guru",
    category: ["AI"],
    intro: "GPT Guru is a next-generation blockchain AI tool empowering Web 3.0 communities fuelling their creativity and productivity like never before !",
    date: "",
    round: "",
    status: "",
    website: "https://gptguru.io/",
    twitter: "https://twitter.com/GPTGuru_",
    icon: "icons/gpt-guru.png"
  },
  {
    id: "mogaland",
    name: "MogaLand",
    category: ["GameFi"],
    intro: "World’s first game-based #financialliteracy protocol where fun fuels financial freedom",
    date: "",
    round: "",
    status: "",
    website: "https://mogaland.io/",
    twitter: "https://twitter.com/Mogaland_io",
    icon: "icons/mogaland.png"
  },
  {
    id: "mni-corp",
    name: "MNI Corp",
    category: ["DApp"],
    intro: "Real-world returns from real-world assets. Bridging conventional to digital.",
    date: "",
    round: "",
    status: "",
    website: "https://mnicorp.io/",
    twitter: "https://twitter.com/MNICorp",
    icon: "icons/mni-corp.png"
  },
  {
    id: "dexcheck",
    name: "DexCheck",
    category: ["DApp"],
    intro: "Elevate your trading game with Next-Gen Crypto & NFT AI-Enhanced Analytics Tools",
    date: "",
    round: "",
    status: "",
    website: "https://dexcheck.ai/",
    twitter: "https://twitter.com/DexCheck_io",
    icon: "icons/dexcheck.png"
  },
  {
    id: "toscale",
    name: "Toscale",
    category: ["DApp"],
    intro: "Web #terminal & #trading #bots designer for #crypto Manage your #blockchain assets on #exchanges via the API from one window on http://toscale.io",
    date: "",
    round: "",
    status: "",
    website: "https://toscale.io/",
    twitter: "https://twitter.com/toscale_io",
    icon: "icons/toscale.png"
  },
  {
    id: "polymer-labs",
    name: "Polymer Labs",
    category: ["DAppDeFi"],
    intro: "Polymer Labs . Establishing the next generation of the internet, by scaling IBC interoperability to all blockchains.",
    date: "",
    round: "",
    status: "",
    website: "https://polymerlabs.org/",
    twitter: "https://twitter.com/Polymer_Labs",
    icon: "icons/polymer-labs.png"
  },
  {
    id: "orbofi",
    name: "Orbofi",
    category: ["AI"],
    intro: "The most adopted #AI content engine in web3, for AI agents, apps, and online communities. $OBI",
    date: "",
    round: "",
    status: "",
    website: "https://orbofi.com/",
    twitter: "https://twitter.com/Orbofi",
    icon: "icons/orbofi.png"
  },
  {
    id: "eldarune",
    name: "Eldarune",
    category: ["GameFi"],
    intro: "Interoperable Web3 Gaming Studio",
    date: "",
    round: "",
    status: "",
    website: "https://eldarune.com/",
    twitter: "https://twitter.com/PlayEldarune",
    icon: "icons/eldarune.png"
  },
  {
    id: "trollx",
    name: "TrollX",
    category: ["L2"],
    intro: "",
    date: "",
    round: "",
    status: "",
    website: "https://troll2.xyz/",
    twitter: "https://twitter.com/TROLLXT",
    icon: "icons/trollx.png"
  },
  {
    id: "sadhguru-sadupdesh",
    name: "Sadhguru Sadupdesh",
    category: ["Marketplace"],
    intro: "Our mission & aim is to make Sadhguru Sadupdesh (Knowledgeable spiritual verse) reach as many people possible and make every human reach its highest potential",
    date: "",
    round: "",
    status: "",
    website: "https://twitter.com",
    twitter: "https://twitter.com/SSadupdesh",
    icon: "icons/sadhguru-sadupdesh.png"
  },
  {
    id: "privasea",
    name: "Privasea",
    category: ["AIDeFi"],
    intro: "Worldwide privacy compliance enabled through FHE",
    date: "",
    round: "",
    status: "",
    website: "https://pivasea.ai/",
    twitter: "https://twitter.com/Privasea_ai",
    icon: "icons/privasea.png"
  },
  {
    id: "aradena-games",
    name: "Aradena Games",
    category: ["GameFi"],
    intro: "Building the next generation of trading card gaming | Immersive PvP Battles with a 3D Hex Battlefield & more",
    date: "",
    round: "",
    status: "",
    website: "https://aradena.io/",
    twitter: "https://twitter.com/AradenaWarrior",
    icon: "icons/aradena-games.png"
  },
  {
    id: "xandar-games",
    name: "Xandar Games",
    category: ["GameFiNFTAI"],
    intro: "A revolutionary Web3-powered MMORPG that brings together blockchain, NFTs, and AI to create an immersive gaming universe. Powered by @SkaleNetwork",
    date: "",
    round: "",
    status: "",
    website: "https://xandar.games/",
    twitter: "https://twitter.com/xandargames",
    icon: "icons/xandar-games.png"
  },
  {
    id: "finblox",
    name: "Finblox",
    category: ["DAppNFT"],
    intro: "Earn sustainable rewards on your Bitcoin & crypto by staking and trading. #RWA #Launchpad",
    date: "",
    round: "",
    status: "",
    website: "https://finblox.com/",
    twitter: "https://finblox.com/",
    icon: "icons/finblox.png"
  },
  {
    id: "rexbit",
    name: "Rexbit",
    category: ["Exchange"],
    intro: "Multichain DEX of perpetual futures. DeFi + Centralized Experience",
    date: "",
    round: "",
    status: "",
    website: "https://rexbit.exchange/",
    twitter: "https://twitter.com/rexbit_exchange",
    icon: "icons/rexbit.png"
  },
  {
    id: "kaichain",
    name: "KaiChain",
    category: ["L2"],
    intro: "#Kaichain is up to 10,000x faster than Ethereum with almost close to free gas, EVM compatible and carbon free blockchain. $KEC",
    date: "",
    round: "",
    status: "",
    website: "https://kaichain.net/",
    twitter: "https://twitter.com/KaiChain1",
    icon: "icons/kaichain.png"
  },
  {
    id: "mc2-finance",
    name: "MC2 Finance",
    category: ["L2DeFi"],
    intro: "Where experienced crypto traders can share their portfolio strategies and more novice users can copy their strategies.",
    date: "",
    round: "",
    status: "",
    website: "https://www.mc2.fi",
    twitter: "https://twitter.com/mcsquaredfi",
    icon: "icons/mc2-finance.png"
  },
  {
    id: "dein",
    name: "DeIN",
    category: ["DeFi"],
    intro: "Decentralized Insurance Network Insurance infrastructure on all chains.",
    date: "",
    round: "",
    status: "",
    website: "https://dein.fi/",
    twitter: "https://twitter.com/DEIN_fi",
    icon: "icons/dein.png"
  },
  {
    id: "layerzero-labs",
    name: "LayerZero Labs",
    category: ["L2"],
    intro: "We're building LayerZero, an omnichain interoperability protocol.",
    date: "",
    round: "",
    status: "",
    website: "https://layerzero.network/",
    twitter: "https://twitter.com/LayerZero_Labs",
    icon: "icons/layerzero-labs.png"
  },
  {
    id: "zkcross",
    name: "ZKcross",
    category: ["L2"],
    intro: "modular rollup based on zkWasm.",
    date: "",
    round: "",
    status: "",
    website: "https://zkcross.org/",
    twitter: "https://twitter.com/thezkcross",
    icon: "icons/zkcross.png"
  },
  {
    id: "alterverse",
    name: "Alterverse",
    category: ["GameFi"],
    intro: "A world and game creation platform.",
    date: "",
    round: "",
    status: "",
    website: "https://alterverse.com/",
    twitter: "https://twitter.com/AlterVerseGame",
    icon: "icons/alterverse.png"
  },
  {
    id: "playzap",
    name: "PlayZap",
    category: ["GameFi"],
    intro: "Free to Play. Skill to Earn. A web3 gaming platform for casual competitive gamers powered by $PZP with 1 Million Players!",
    date: "",
    round: "",
    status: "",
    website: "https://playzap.games/",
    twitter: "https://twitter.com/PlayZapGames",
    icon: "icons/playzap.png"
  },
  {
    id: "rareround",
    name: "RareRound",
    category: ["GameFi"],
    intro: "Rarebet is the future of crypto casinos & betting. Wen token?",
    date: "",
    round: "",
    status: "",
    website: "https://rare.bet/",
    twitter: "https://twitter.com/rarebetcom",
    icon: "icons/rareround.png"
  },
  {
    id: "reign-of-terror",
    name: "Reign of Terror",
    category: ["GameFi"],
    intro: "A cyberpunk game world with multiple games",
    date: "",
    round: "",
    status: "",
    website: "https://reignofterror.io/",
    twitter: "https://twitter.com/RoTTheGame",
    icon: "icons/reign-of-terror.png"
  },
  {
    id: "chaingpt",
    name: "ChainGPT",
    category: ["AIL2"],
    intro: "ChainGPT #1 ranked AI infrastructure for Blockchain, Crypto & Web3.Unleash the power of Blockchain AI with ChainGPT.",
    date: "",
    round: "",
    status: "",
    website: "https://chaingpt.org/",
    twitter: "https://twitter.com/Chain_GPT",
    icon: "icons/chaingpt.png"
  },
  {
    id: "menthol-protocol",
    name: "Menthol Protocol",
    category: ["L1Payment"],
    intro: "Menthol Protocol is the first multi-chain decentralized regeneration protocol that will automatically offset carbon emissions.",
    date: "",
    round: "",
    status: "",
    website: "https://mentholprotocol.com/",
    twitter: "https://twitter.com/MentholProtocol",
    icon: "icons/menthol-protocol.png"
  },
  {
    id: "sheertopia",
    name: "Sheertopia",
    category: ["GameFi"],
    intro: "Immersive AI gaming | Power to the player",
    date: "",
    round: "",
    status: "",
    website: "https://projectlambo.io/",
    twitter: "https://twitter.com/projectlamboio",
    icon: "icons/sheertopia.png"
  },
  {
    id: "alaska-gold-rush",
    name: "Alaska Gold Rush",
    category: ["GameFi"],
    intro: "First real AAA+ gaming web3 lore.",
    date: "",
    round: "",
    status: "",
    website: "https://alaskagoldrush.io/",
    twitter: "https://twitter.com/alaska_game",
    icon: "icons/alaska-gold-rush.png"
  },
  {
    id: "octo-gaming",
    name: "Octo Gaming",
    category: ["GameFi"],
    intro: "Gaming App with +3 M users",
    date: "",
    round: "",
    status: "",
    website: "https://otto-gaming.com/",
    twitter: "https://twitter.com/Octo8gaming",
    icon: "icons/octo-gaming.png"
  },
  {
    id: "avem-finance",
    name: "AVEM Finance",
    category: ["DeFi"],
    intro: "The Blockchain for Business",
    date: "",
    round: "",
    status: "",
    website: "https://avem.finance/",
    twitter: "https://twitter.com/avemfinance",
    icon: "icons/avem-finance.png"
  },
  {
    id: "hypercycle-ai",
    name: "HyperCycle AI",
    category: ["AIL1"],
    intro: "The blockchain network designed to supply massively scalable, low-cost infrastructure for decentralized AI, and other applications.",
    date: "",
    round: "",
    status: "",
    website: "https://hypercycle.ai/",
    twitter: "https://twitter.com/Hypercycle_AI",
    icon: "icons/hypercycle-ai.png"
  },
  {
    id: "winr-games",
    name: "Winr Games",
    category: ["GameFi"],
    intro: "Decentralized iGaming infrastructure.",
    date: "",
    round: "",
    status: "",
    website: "https://winr.games/",
    twitter: "https://twitter.com/WINRProtocol",
    icon: "icons/winr-games.png"
  },
  {
    id: "mantera-protocol",
    name: "Mantera Protocol",
    category: ["L2"],
    intro: "",
    date: "",
    round: "",
    status: "",
    website: "https://matr.world/",
    twitter: "https://twitter.com/matr_world",
    icon: "icons/mantera-protocol.png"
  },
  {
    id: "maximum-protocol",
    name: "Maximum Protocol",
    category: ["DApp"],
    intro: "We are an analytics-driven portfolio optimization tool. It offers a simple, intuitive user experience to help investors make the most of their crypto portfolio.",
    date: "",
    round: "",
    status: "",
    website: "https://www.maximumprotocol.io",
    twitter: "https://twitter.com/m3p_finance",
    icon: "icons/maximum-protocol.png"
  },
  {
    id: "hypermove",
    name: "HyperMove",
    category: ["GameFi"],
    intro: "Hyper move is a decentralized blockchain oriented #P2E gaming platform",
    date: "",
    round: "",
    status: "",
    website: "https://hypermove.io/",
    twitter: "https://twitter.com/hypermove_io",
    icon: "icons/hypermove.png"
  }
];

